# Generated by scripts/sdk/generate-py.ts. Do not edit.
#
# Every operation under /v1 that answers with JSON. The four that stream —
# both event streams, the artifact archive, and an artifact's bytes — are
# deliberately absent and hand-written in ../lib, because a generated method
# would parse a live connection as JSON.
#
# sdk/python/drift.test.ts regenerates this file and fails on any difference.

from __future__ import annotations

from typing import Any, Dict, List, Literal, NotRequired, Optional, TypedDict, Union
from urllib.parse import quote

from .._transport import Transport

# ── Wire types ──────────────────────────────────────────────────────────────

class Agent(TypedDict):
    object: Literal["agent"]
    id: str
    """Ours. Pass it as `agent.id` when creating a session."""
    name: str
    """Yours, for recognising it. Not an identifier."""
    model: NotRequired[Union[str, None]]
    """The model sessions from this agent run on, unless they override it."""
    model_credential_id: NotRequired[Union[str, None]]
    """The connection to run on. Null uses the organization's default."""
    instructions: NotRequired[Union[str, None]]
    """Standing instructions given to every session started from this agent."""
    tools: NotRequired[List["Tool"]]
    """Tools every session started from this agent gets, unless it replaces them. Secrets are withheld — see `redacted` on an entry."""
    text: NotRequired[Union[Dict[str, Any], None]]
    """Output shaping copied into every session started from this agent."""
    created_at: NotRequired[int]
    """Unix milliseconds."""


class AgentConfig(TypedDict):
    """What runs, and how freely."""

    id: NotRequired[str]
    """An agent to inherit from. Per-field overrides still apply."""
    model: NotRequired[str]
    """Must be one the chosen credential runs."""
    model_credential_id: NotRequired[str]
    """Omit to use the organization's default."""
    instructions: NotRequired[Union[str, None]]
    """Standing instructions for every turn. `null` clears an inherited one."""
    approval_mode: NotRequired[Literal["auto", "per_step", "read_only", "plan"]]
    """How much the agent may do without asking."""
    permission_rules: NotRequired[List[Dict[str, Any]]]
    """Path rules evaluated before a write."""
    tools: NotRequired[List["ToolRequest"]]
    text: NotRequired["TextConfig"]


class AgentCreateRequest(TypedDict):
    name: str
    """Yours, for recognising it."""
    model: NotRequired[str]
    model_credential_id: NotRequired[str]
    instructions: NotRequired[str]
    tools: NotRequired[List["ToolRequest"]]
    text: NotRequired["TextConfig"]


class AgentList(TypedDict):
    object: Literal["list"]
    data: List["Agent"]


class AgentsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class Artifact(TypedDict):
    """An immutable copy of a file a turn published. Survives the sandbox being paused or reclaimed."""

    object: Literal["artifact"]
    id: str
    """Ours. Use it to fetch the bytes."""
    session_id: str
    """The session that produced it."""
    turn_id: str
    """The turn that published it."""
    path: str
    """Where it was in the workspace when it was published."""
    size_bytes: int
    """Of the stored copy."""
    content_type: NotRequired[str]
    """Guessed from the path. `application/octet-stream` when unrecognised."""
    created_at: NotRequired[int]
    """Unix milliseconds, when it was published."""


class ArtifactList(TypedDict):
    object: Literal["list"]
    data: List["Artifact"]
    has_more: NotRequired[bool]
    last_id: NotRequired[Union[str, None]]


class Deleted(TypedDict):
    object: Literal["session.deleted"]
    id: str
    deleted: bool


class EnvironmentProfile(TypedDict):
    object: Literal["environment_profile"]
    id: str
    name: str
    is_default: NotRequired[bool]
    variable_count: NotRequired[Union[int, None]]


class EnvironmentProfileList(TypedDict):
    object: Literal["list"]
    data: List["EnvironmentProfile"]


class EnvironmentProfilesListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class EnvironmentTemplate(TypedDict):
    """A named configuration copied into a session at creation. Changing or deleting it does not affect sessions already created from it."""

    object: Literal["environment_template"]
    id: str
    name: str
    tools: NotRequired[List["Tool"]]
    """Tools every session started from this agent gets, unless it replaces them. Secrets are withheld — see `redacted` on an entry."""
    text: NotRequired[Union[Dict[str, Any], None]]
    """Output shaping copied into every session started from this agent."""
    created_at: NotRequired[int]


class EnvironmentTemplateList(TypedDict):
    object: Literal["list"]
    data: List["EnvironmentTemplate"]


class EnvironmentTemplatesListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class Error(TypedDict):
    """Every refusal this API makes, in one shape."""

    error: "ErrorError"
    """Always present on a failure, and the only thing present."""


class ErrorError(TypedDict):
    """Always present on a failure, and the only thing present."""

    code: Literal["invalid_request", "authentication_error", "permission_denied", "not_found", "method_not_allowed", "conflict", "queue_full", "rate_limit_exceeded", "project_limit_exceeded", "context_length_exceeded", "provider_error", "provider_unauthorized", "sandbox_error", "sandbox_unavailable", "directory_unavailable", "workspace_recovery_failed", "bridge_incompatible", "internal_error"]
    message: str
    request_id: str
    """Also on the x-request-id header. Quote it when reporting a problem."""


class EventsRequest(TypedDict):
    """One event per request. Batching has no meaning while the vocabulary is this small."""

    events: List["InputEvent"]


class FilesRequest(TypedDict):
    files: List["SeedFile"]


class Fork(TypedDict):
    """A new session branched from another, with its workspace and transcript. It spends a session slot like any other, and is refused by the same ceiling with the same code."""

    forked_from: NotRequired[str]
    """The session this was branched from. It is untouched."""
    workspace_copied: NotRequired[bool]
    """Whether the workspace came with it. False means the fork starts empty — a fork is still useful without it, and believing the files are there when they are not is worse than knowing."""


class Health(TypedDict):
    object: Literal["health"]
    status: Literal["ok"]
    version: Literal["v1"]
    scopes: List[Literal["cli", "sessions:read", "sessions:write", "tools:respond", "artifacts:read", "credentials:write"]]


class InputAccepted(TypedDict):
    object: Literal["input.accepted"]
    session_id: str
    type: Literal["input.message", "input.cancel", "input.tool_result", "input.steer"]
    outcome: NotRequired[Literal["accepted", "already_resolved", "not_delivered"]]
    """For input.tool_result."""
    queued: NotRequired[bool]
    """The session was busy; the message is durably queued and will run."""
    queue_position: NotRequired[Union[int, None]]


class InputEvent(TypedDict):
    """The six things you can send a session. One per request."""

    type: Literal["input.message", "input.tool_result", "input.approval", "input.question_answer", "input.steer", "input.cancel"]
    content: NotRequired[Any]
    """For `input.message` and `input.steer`: a string, or an array of `{type,text}` parts."""
    turn_id: NotRequired[str]
    """For `input.tool_result`: copied from the required action."""
    call_id: NotRequired[str]
    """For `input.tool_result`, `input.approval` and `input.question_answer`: copied from the required action."""
    success: NotRequired[bool]
    """For `input.tool_result`: whether your function worked."""
    output: NotRequired[str]
    """For a successful `input.tool_result`. Serialise JSON yourself."""
    error: NotRequired[str]
    """For a failed `input.tool_result`. Never send a thrown message — it reaches the model."""
    approved: NotRequired[bool]
    """For `input.approval`: whether the agent may proceed. Required, and not defaulted either way — denying something you meant to allow is a mistake, and the other direction is worse."""
    answer: NotRequired[str]
    """For `input.question_answer`: what to tell the agent. It reaches the model as written."""


class Item(TypedDict):
    object: Literal["item"]
    id: str
    """Ours. Stable; use it as a paging cursor."""
    session_id: str
    """The session this item belongs to."""
    type: Literal["message", "tool_call", "command_execution", "file_change", "approval", "question", "mcp_unavailable", "error"]
    """What kind of thing happened. Decides which of `content` and `detail` carries the substance. `error` says a run could not start or could not continue, and `detail.message` says why."""
    created_at: int
    """Unix milliseconds."""
    role: NotRequired[Literal["user", "assistant"]]
    """On `message` items only: who said it."""
    content: NotRequired[str]
    """The text of a `message`. Empty on other kinds."""
    detail: NotRequired[Dict[str, Any]]
    """Everything kind-specific: the command run, the path changed, the arguments passed. Shape varies by `type`."""


class ItemList(TypedDict):
    object: Literal["list"]
    data: List["Item"]
    has_more: NotRequired[bool]
    last_id: NotRequired[Union[str, None]]


class ModelConnector(TypedDict):
    object: Literal["model_connector"]
    id: str
    """What to send as `provider` when connecting a key."""
    display_name: str
    default_model: NotRequired[Union[str, None]]
    """What you get by omitting `model`, and what `agent.model` must match unless you name another."""
    key_prefix: NotRequired[Union[str, None]]
    """How this vendor's keys begin. Several vendors share `sk-`, which is why connecting one of those asks for `provider` — this is how you tell which ids collide before sending a secret."""
    key_url: NotRequired[Union[str, None]]
    """Where to get a key."""
    protocol: Literal["anthropic", "openai"]
    """The wire protocol, which decides what a custom `base_url` must speak."""
    default_base_url: NotRequired[Union[str, None]]


class ModelConnectorCatalog(TypedDict):
    """The model providers this deployment can connect. Served without a token, like the OpenAPI document: it describes what the API supports rather than anything inside an organization."""

    object: Literal["list"]
    data: List["ModelConnector"]


class ModelCredential(TypedDict):
    object: Literal["model_credential"]
    id: str
    """Pass as agent.model_credential_id."""
    label: NotRequired[str]
    """Yours, from the Console. For recognising the connection."""
    connector: NotRequired[str]
    """Which provider integration it uses."""
    model: str
    """agent.model must match this."""
    is_default: NotRequired[bool]
    """Whether a session that names no credential gets this one."""
    last4: NotRequired[str]
    """The last four characters of the key. On create only; the key itself is never returned."""
    verified: NotRequired[bool]
    """Whether the provider accepted a probe before this was stored."""


class ModelCredentialCreateRequest(TypedDict):
    key: str
    """The provider key. Verified against the provider before it is stored, and returned nowhere afterwards."""
    provider: NotRequired[str]
    """Which vendor issued the key. Only needed when the prefix does not say: several vendors issue keys starting with `sk-`, and we ask rather than send your secret to vendors you never named."""
    model: NotRequired[str]
    """Omit to accept the connector's default."""
    base_url: NotRequired[str]
    """For `custom`, and for self-hosted or proxied endpoints."""
    label: NotRequired[str]
    """A name for the Console's list. Defaults to the provider's."""
    default: NotRequired[bool]
    """Whether sessions naming no credential get this one. The first connection is always the default. Must be a boolean — a string is refused rather than read as false, because this decides whose bill every future turn lands on."""


class ModelCredentialList(TypedDict):
    object: Literal["list"]
    data: List["ModelCredential"]


class ModelCredentialsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class Preview(TypedDict):
    object: Literal["preview"]
    subdomain: str
    """The label the site is served under."""
    url: str
    """The public address. A Gobare origin, never the sandbox provider's."""
    port: Union[int, None]
    """The workspace port being served."""


class PreviewDeleted(TypedDict):
    object: Literal["preview.deleted"]
    id: str
    deleted: bool


class PreviewPublishRequest(TypedDict):
    subdomain: NotRequired[str]
    """2–63 characters of a–z, 0–9 and hyphens. Omit and one is derived from the session."""


class RequiredAction(TypedDict):
    """Something this session is waiting for. Copy turn_id and call_id into the result you submit."""

    type: Literal["function_call", "approval", "question"]
    """What is being asked of you. `function_call` you answer through the API; `approval` and `question` are answered by a person in the Console."""
    turn_id: str
    """Copy this back when answering."""
    call_id: str
    """Copy this back when answering. It identifies which call the result is for."""
    name: NotRequired[Union[str, None]]
    """The function the agent wants to call, as you declared it."""
    arguments: NotRequired[Any]
    """What it wants to call the function with. Shaped by your own parameter schema."""
    created_at: NotRequired[int]
    """Unix milliseconds, when the agent asked."""
    expires_at: NotRequired[Union[int, None]]
    """Unix milliseconds, when this stops being waited for — set from the tool's own `timeout_seconds`. Null, the default, means it waits indefinitely. Past this the call is answered as failed and the turn continues; the turn itself does not fail."""


class SeedFile(TypedDict):
    """One file, inline. There is no Files API to reference and we do not fetch URLs on your behalf; for a large input use `environment.repo`."""

    type: NotRequired[Literal["inline"]]
    """Optional, and `inline` is the only value. Named rather than defaulted: a caller sending `file_id` has a file we cannot reach, and treating it as inline would hand them an empty workspace with no reason why."""
    path: str
    """Where in the workspace to write it. Confined to the workspace directory."""
    data: str
    """The file's bytes, base64. Always base64, including for text — one encoding to get right rather than two."""


class Session(TypedDict):
    object: Literal["session"]
    id: str
    """Ours, not yours. Use `metadata` to carry your own identifier."""
    title: NotRequired[Union[str, None]]
    """A label for people. Set it yourself; nothing derives one."""
    status: Literal["idle", "working", "requires_action", "failed"]
    """`idle` accepts input. `working` is running a turn. `requires_action` is waiting on you — see `required_actions`. `failed` is the last turn's outcome, not a dead session."""
    created_at: int
    """Unix milliseconds."""
    updated_at: int
    """Unix milliseconds. Moves on any change, including the workspace waking."""
    source: NotRequired[Literal["api", "console", "cli", null]]
    """Which door created this session. Null on sessions predating the field."""
    created_by_token: NotRequired[Union[str, None]]
    """The id of the access token that created it — never its secret."""
    agent: "SessionAgent"
    """What is running, and how freely."""
    environment: "SessionEnvironment"
    """The workspace: its state, where the agent works, and the repository bound to it."""
    preview: "SessionPreview"
    """Addresses for whatever the agent is serving. See preview.md."""
    required_actions: NotRequired[List["RequiredAction"]]
    """Everything the session is waiting on you for. Authoritative — not a replay of events, so a caller that restarted gets the same complete answer."""


class SessionAgent(TypedDict):
    """What is running, and how freely."""

    model: NotRequired[Union[str, None]]
    """The model this session is bound to. Fixed at creation."""
    model_credential_id: NotRequired[Union[str, None]]
    """The connection it runs on. `GET /v1/model-credentials` lists them."""
    approval_mode: NotRequired[Union[str, None]]
    """How much the agent may do without asking."""
    instructions: NotRequired[Union[str, None]]
    permission_rules: NotRequired[List[Dict[str, Any]]]
    tools: NotRequired[List[Dict[str, Any]]]
    """What this session can call, as you configured it, with any secrets removed. On the single-session read only — a page of sessions does not carry it."""


class SessionCreateRequest(TypedDict):
    """Everything optional. A session with only a model is a complete session."""

    agent: NotRequired["AgentConfig"]
    environment: NotRequired["SessionCreateRequestEnvironment"]
    """What the workspace starts with."""
    metadata: NotRequired[Dict[str, str]]
    """Your own labels. Returned unchanged; never interpreted."""
    input: NotRequired[str]
    """An opening message. All or nothing — if it cannot be accepted the session is not created either."""
    title: NotRequired[str]
    """A label for people."""


class SessionCreateRequestEnvironment(TypedDict):
    """What the workspace starts with."""

    template_id: NotRequired[str]
    """Deprecated name for an agent id."""
    profiles: NotRequired[List[str]]
    """Environment-variable group ids. GET /v1/environment-profiles lists them."""
    repo: NotRequired[str]
    """`owner/name`. A URL is refused; the branch is reported by the clone, not chosen."""
    files: NotRequired[List["SeedFile"]]
    """Files to place in the workspace before the first turn."""


class SessionEnvironment(TypedDict):
    """The workspace: its state, where the agent works, and the repository bound to it."""

    type: NotRequired[Literal["sandbox"]]
    state: NotRequired[Literal["unknown", "running", "paused", "destroyed", "recovering", "recovery_failed"]]
    """Where the workspace is. `unknown` until it first reports — a session is created before its sandbox exists, so this is what you see immediately after POST /v1/sessions. `running` is usable; `paused` is idle and woken by the next thing you send; `destroyed` is reclaimed and will be rebuilt on demand; `recovering` and `recovery_failed` are a rebuild in progress and one that gave up. A value outside this set is reported as null rather than passed through."""
    workspace_directory: NotRequired[str]
    repo: NotRequired[Union["SessionEnvironmentRepo", None]]
    """The repository bound to this session, once one is. Null when none was asked for."""


class SessionEnvironmentRepo(TypedDict):
    """The repository bound to this session, once one is. Null when none was asked for."""

    full_name: NotRequired[str]
    """owner/name, as given."""
    branch: NotRequired[Union[str, None]]
    """Reported by the clone, not chosen. Null until the workspace comes up."""
    clone_error: NotRequired[Union[str, None]]
    """Why the clone did not happen, when it did not."""


class SessionList(TypedDict):
    object: Literal["list"]
    data: List["Session"]
    has_more: NotRequired[bool]
    last_id: NotRequired[Union[str, None]]


class SessionPatchRequest(TypedDict):
    """Only the fields present are changed."""

    title: NotRequired[Union[str, None]]
    metadata: NotRequired[Union[Dict[str, str], None]]
    """`null` clears every label."""
    agent: NotRequired["SessionPatchRequestAgent"]


class SessionPatchRequestAgent(TypedDict):
    model: NotRequired[str]
    """Move this running session to another connection. Send with `model_credential_id`; the workspace and the transcript are kept."""
    model_credential_id: NotRequired[str]
    """The connection to move to. It must offer the named model — one connection runs one model."""
    instructions: NotRequired[Union[str, None]]
    approval_mode: NotRequired[Literal["auto", "per_step", "read_only", "plan"]]
    permission_rules: NotRequired[List[Dict[str, Any]]]


class SessionPreview(TypedDict):
    """Addresses for whatever the agent is serving. See preview.md."""

    url: NotRequired[Union[str, None]]
    port: NotRequired[Union[int, None]]
    published_url: NotRequired[Union[str, None]]


class SessionsArtifactsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    order: NotRequired[Literal["asc", "desc"]]
    """Newest first (`desc`, the default) or oldest first (`asc`)."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""
    turn_id: NotRequired[str]
    """Only what this turn published."""


class SessionsFilesContentRetrieveQuery(TypedDict):
    path: NotRequired[str]
    """Relative to the workspace directory."""


class SessionsItemsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    order: NotRequired[Literal["asc", "desc"]]
    """Newest first (`desc`, the default) or oldest first (`asc`)."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class SessionsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    order: NotRequired[Literal["asc", "desc"]]
    """Newest first (`desc`, the default) or oldest first (`asc`)."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""
    status: NotRequired[Literal["idle", "working", "requires_action", "failed"]]
    """Only sessions in this state. `requires_action` is the one to ask for after a restart: it is everything waiting on your code."""
    metadata: NotRequired[str]
    """One of your own labels, as `key:value` — `?metadata=job:8842`. Finds the session for a job without keeping a map of your own."""


class SessionsTurnsListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    order: NotRequired[Literal["asc", "desc"]]
    """Newest first (`desc`, the default) or oldest first (`asc`)."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class TextConfig(TypedDict):
    """Shaping the final message."""

    verbosity: NotRequired[Literal["low", "medium", "high"]]
    """How much the agent says when it is done."""
    format: NotRequired["TextConfigFormat"]
    """Asked for, not enforced — see design-decisions."""


class TextConfigFormat(TypedDict):
    """Asked for, not enforced — see design-decisions."""

    type: NotRequired[Literal["json_schema"]]
    schema: NotRequired[Dict[str, Any]]
    """JSON Schema the final message should conform to."""


class Tool(TypedDict):
    type: Literal["mcp", "function"]
    name: str
    """Unique across both types: the agent sees one list."""
    url: NotRequired[str]
    """mcp: the server's address. Exclusive with `command`."""
    command: NotRequired[str]
    """mcp: a command run inside the sandbox. Exclusive with `url`."""
    args: NotRequired[List[str]]
    """mcp: arguments for `command`."""
    allowed_tools: NotRequired[List[str]]
    """mcp: restrict the agent to these tools from this server. Absent means all of them."""
    required: NotRequired[bool]
    """mcp: the session fails if this server will not connect. Absent means optional, which produces an `mcp.unavailable` event instead."""
    redacted: NotRequired[List[str]]
    """Names of the secret values withheld from this response, such as `authorization` or `headers.x-api-key`. Not a request field: sending it back is refused, so an edited read-back cannot silently drop your credentials."""
    description: NotRequired[str]
    """function: what the function is for. The model reads it."""
    parameters: NotRequired[Dict[str, Any]]
    """function: a JSON Schema for the arguments. Carried unexamined."""
    timeout_seconds: NotRequired[int]
    """function: how long to wait for your process to answer this call."""


class ToolConfig(TypedDict):
    object: Literal["session.tools"]
    session_id: str
    """The session this configuration applies to."""
    tools: NotRequired[List["Tool"]]
    """The configuration as sent, in the same vocabulary: one entry per tool, each with a `type` of `mcp` or `function`. Secret values are withheld — see `redacted`."""
    text: NotRequired[Union["ToolConfigText", None]]
    """Output shaping, or null when none was set. Asked of the model, not enforced."""


class ToolConfigText(TypedDict):
    """Output shaping, or null when none was set. Asked of the model, not enforced."""

    verbosity: NotRequired[Literal["low", "medium", "high"]]
    format: NotRequired[Dict[str, Any]]
    """`{type: "json_schema", schema: {…}}` — the shape the model is asked to answer in."""


class ToolRequest(TypedDict):
    """One tool. `type` decides which of the two shapes below applies; the fields of the other are refused rather than ignored."""

    type: Literal["function", "mcp"]
    name: str
    """What the agent calls it. Copied back to you as `name`."""
    description: NotRequired[str]
    """`function` only. Read by the model to decide when to call it."""
    parameters: NotRequired[Dict[str, Any]]
    """`function` only. JSON Schema for the arguments."""
    timeout_seconds: NotRequired[int]
    """`function` only. How long a required action may stay unanswered."""
    url: NotRequired[str]
    """`mcp` only. http or https endpoint of the server."""
    command: NotRequired[str]
    """`mcp` only. A server started inside the workspace instead of reached over the network."""
    args: NotRequired[List[str]]
    """`mcp` only. Arguments for `command`."""
    allowed_tools: NotRequired[List[str]]
    """`mcp` only. Narrow the server to these tool names."""
    required: NotRequired[bool]
    """`mcp` only. `true` fails the session loudly when the server will not connect; `false` lets the turn continue with fewer tools and an `mcp.unavailable` event. Must be a boolean — a string is refused rather than read as false."""
    authorization: NotRequired[str]
    """`mcp` only. Sent to the server, never returned; a read-back names it under `redacted`."""
    headers: NotRequired[Dict[str, str]]
    """`mcp` only. Also withheld from a read-back."""


class ToolsRequest(TypedDict):
    """What the agent may call. Replaces the session's whole configuration — entries are not merged with what is already there."""

    tools: NotRequired[List["ToolRequest"]]
    text: NotRequired["TextConfig"]


class Turn(TypedDict):
    object: Literal["turn"]
    id: str
    """Ours. Quote it when reporting a problem with this turn."""
    session_id: str
    """The session this turn belongs to."""
    status: Literal["working", "completed", "failed", "cancelled"]
    """`working` covers everything before it settles, including a turn parked on a tool result from you — watch the session's `requires_action` for that, not this field. `completed`, `failed` and `cancelled` are settled; a settled turn never moves again."""
    created_at: int
    """Unix milliseconds, when the input was accepted."""
    started_at: NotRequired[Union[int, None]]
    """When the agent began. Null while queued."""
    completed_at: NotRequired[Union[int, None]]
    """When it settled. Null until it has."""
    artifacts: NotRequired[Literal["pending", "ready", "partial", "failed", null]]
    """Whether this turn's artifacts can be fetched yet. Publication runs after the turn settles, so an empty artifact list under `pending` means not yet, and under `ready` means the turn produced nothing. `partial` means publishing finished and left something behind — read `artifacts_skipped` for what and why."""
    artifacts_skipped: NotRequired[List["TurnArtifactsSkippedItem"]]
    """Files publishing did not take, and why. Empty unless `artifacts` is `partial`. A file past the per-file ceiling, or one that did not fit in what the turn had left, is reported here rather than disappearing."""
    subagent_id: NotRequired[Union[str, None]]
    """Always null today; reserved for delegation."""
    error: NotRequired[Union[Dict[str, Any], None]]
    """Why it failed, when it did. Null otherwise."""


class TurnArtifactsSkippedItem(TypedDict):
    path: str
    """The path inside the workspace, as the agent wrote it."""
    reason: str
    """Why it was not taken. Written for a person, not branched on."""


class TurnList(TypedDict):
    object: Literal["list"]
    data: List["Turn"]
    has_more: NotRequired[bool]
    last_id: NotRequired[Union[str, None]]


class WebhookCreateRequest(TypedDict):
    url: str
    """https only."""
    events: NotRequired[List[str]]
    """Empty or absent means every event."""


class WebhookDeliveryHealth(TypedDict):
    """Whether this endpoint is actually receiving anything. Deliveries are retried six times over roughly nine hours and then given up on; without this, an integration whose endpoint broke found out by noticing it had stopped receiving events — the one thing webhooks exist to stop anyone having to do."""

    pending: int
    """Owed and not yet delivered, including ones waiting on a retry."""
    dead: int
    """Given up on after six attempts. A number that keeps climbing means the endpoint is broken, not busy."""
    last_error: NotRequired[Union[str, None]]
    """Why the most recent one was given up on, as we saw it — a status, or the transport error."""
    last_failed_at: NotRequired[Union[int, None]]
    """Unix milliseconds of that delivery. Null when none has been given up on."""


class WebhookSubscription(TypedDict):
    """An endpoint subscribed to session events. The secret is returned only when it is created."""

    object: Literal["webhook.subscription"]
    id: str
    url: str
    """Where deliveries are POSTed. https only."""
    events: List[str]
    """What this endpoint is subscribed to."""
    active: bool
    created_at: NotRequired[int]
    """Unix milliseconds."""
    delivery: NotRequired["WebhookDeliveryHealth"]


class WebhookSubscriptionCreated(TypedDict):
    """The secret appears in this response only. Store it; it cannot be shown again."""

    object: Literal["webhook.subscription"]
    id: str
    """Ours. Use it to delete the subscription."""
    url: str
    """Where deliveries go. Must be https."""
    events: List[str]
    """Which events to deliver. An empty list means all of them."""
    active: NotRequired[bool]
    """False once deliveries have been given up on. See webhooks.md on retries and dead letters."""
    secret: str
    """Recompute x-gobare-signature as HMAC-SHA256 over `<timestamp>.<body>`."""


class WebhookSubscriptionList(TypedDict):
    object: Literal["list"]
    data: List["WebhookSubscription"]


class WebhooksListQuery(TypedDict):
    limit: NotRequired[int]
    """How many to return, 1–100. Default 20."""
    after: NotRequired[str]
    """The `last_id` of the previous page. A cursor this collection cannot place — expired, deleted, or never issued — answers with an empty page rather than starting over, so a paging loop ends instead of repeating itself."""


class WorkspaceFile(TypedDict):
    object: Literal["workspace_file"]
    path: str
    """Relative to the workspace directory."""
    type: Literal["file", "directory"]
    size_bytes: NotRequired[Union[int, None]]
    """Null for a directory."""
    readable: NotRequired[bool]
    """False for a directory, and for paths this API withholds — environment files and key material."""


class WorkspaceFileContent(TypedDict):
    object: Literal["workspace_file.content"]
    path: str
    captured_at: NotRequired[int]
    """Unix milliseconds of the snapshot this came from."""
    content: str
    """Text as text; anything else base64. `encoding` says which."""
    encoding: Literal["utf8", "base64"]
    truncated: NotRequired[bool]
    """Text past the inline ceiling is cut. Only ever true for text."""


class WorkspaceFileList(TypedDict):
    """What was written into the workspace. A path that was already there has been overwritten — that is what the request asked for."""

    object: Literal["list"]
    data: List["WorkspaceFileListDataItem"]


class WorkspaceFileListDataItem(TypedDict):
    object: Literal["workspace_file"]
    path: str
    size_bytes: int


class WorkspaceFileTree(TypedDict):
    """The files in a session's workspace, as of the last snapshot. Not the live sandbox — `captured_at` says which moment this is, because reading a stale file and believing it current is the failure this field exists to prevent."""

    object: Literal["list"]
    data: List["WorkspaceFile"]
    captured_at: NotRequired[Union[int, None]]
    """Unix milliseconds of the snapshot. Null means none has been taken, which is not the same as an empty workspace."""
    state: Literal["ready", "missing"]
    """`missing` means there is no snapshot yet — call POST /files/refresh."""
    truncated: NotRequired[bool]
    """The archive is read with a byte ceiling; past it the listing stops."""


# ── Resources ───────────────────────────────────────────────────────────────

class HealthResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def retrieve(self, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Health":
        """
        Check the access token and report what it may do.

        ``GET /v1/health``
        """
        return self._transport.request(
            "GET",
            f"/health",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsTurnsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, session_id: str, *, query: Optional["SessionsTurnsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "TurnList":
        """
        List a session's turns.

        ``GET /v1/sessions/{session_id}/turns``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/turns",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, session_id: str, turn_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Turn":
        """
        Retrieve one turn.

        ``GET /v1/sessions/{session_id}/turns/{turn_id}``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/turns/{quote(turn_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsItemsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, session_id: str, *, query: Optional["SessionsItemsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ItemList":
        """
        List a session's durable items.

        ``GET /v1/sessions/{session_id}/items``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/items",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsForkResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Fork":
        """
        Branch a session, workspace and transcript included.

        ``POST /v1/sessions/{session_id}/fork``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/sessions/{quote(session_id, safe='')}/fork",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsToolsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def replace(self, session_id: str, body: "ToolsRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ToolConfig":
        """
        Replace a session's tool configuration.

        ``PUT /v1/sessions/{session_id}/tools``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "PUT",
            f"/sessions/{quote(session_id, safe='')}/tools",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ToolConfig":
        """
        Read a session's tool configuration.

        ``GET /v1/sessions/{session_id}/tools``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/tools",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsEventsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, session_id: str, body: "EventsRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "InputAccepted":
        """
        Send input to a session: a message, a cancellation, or a tool result.

        ``POST /v1/sessions/{session_id}/events``
        Answers 202.
        """
        return self._transport.request(
            "POST",
            f"/sessions/{quote(session_id, safe='')}/events",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsArtifactsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, session_id: str, artifact_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Delete a published artifact.

        ``DELETE /v1/sessions/{session_id}/artifacts/{artifact_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/sessions/{quote(session_id, safe='')}/artifacts/{quote(artifact_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, session_id: str, *, query: Optional["SessionsArtifactsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ArtifactList":
        """
        List files this session's turns published.

        ``GET /v1/sessions/{session_id}/artifacts``
        Needs the ``artifacts:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/artifacts",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, session_id: str, artifact_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Artifact":
        """
        Retrieve one artifact's metadata.

        ``GET /v1/sessions/{session_id}/artifacts/{artifact_id}``
        Needs the ``artifacts:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/artifacts/{quote(artifact_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsFilesContentResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def retrieve(self, session_id: str, *, query: Optional["SessionsFilesContentRetrieveQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WorkspaceFileContent":
        """
        Read one file from a session's workspace.

        ``GET /v1/sessions/{session_id}/files/content``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/files/content",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsFilesRefreshResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WorkspaceFileTree":
        """
        Capture a fresh snapshot of the workspace, so a read sees current files.

        ``POST /v1/sessions/{session_id}/files/refresh``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "POST",
            f"/sessions/{quote(session_id, safe='')}/files/refresh",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsFilesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.content: SessionsFilesContentResource = SessionsFilesContentResource(transport)
        self.refresh: SessionsFilesRefreshResource = SessionsFilesRefreshResource(transport)

    def create(self, session_id: str, body: "FilesRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WorkspaceFileList":
        """
        Write files into a running session's workspace.

        ``POST /v1/sessions/{session_id}/files``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "POST",
            f"/sessions/{quote(session_id, safe='')}/files",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WorkspaceFileTree":
        """
        List the files in a session's workspace.

        ``GET /v1/sessions/{session_id}/files``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}/files",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsPreviewResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, session_id: str, body: "PreviewPublishRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Preview":
        """
        Publish this session's preview at a public URL.

        ``POST /v1/sessions/{session_id}/preview``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/sessions/{quote(session_id, safe='')}/preview",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "PreviewDeleted":
        """
        Take this session's preview off its public URL.

        ``DELETE /v1/sessions/{session_id}/preview``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/sessions/{quote(session_id, safe='')}/preview",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class SessionsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.turns: SessionsTurnsResource = SessionsTurnsResource(transport)
        self.items: SessionsItemsResource = SessionsItemsResource(transport)
        self.fork: SessionsForkResource = SessionsForkResource(transport)
        self.tools: SessionsToolsResource = SessionsToolsResource(transport)
        self.events: SessionsEventsResource = SessionsEventsResource(transport)
        self.artifacts: SessionsArtifactsResource = SessionsArtifactsResource(transport)
        self.files: SessionsFilesResource = SessionsFilesResource(transport)
        self.preview: SessionsPreviewResource = SessionsPreviewResource(transport)

    def create(self, body: "SessionCreateRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Session":
        """
        Create a session, optionally with an opening message.

        ``POST /v1/sessions``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/sessions",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Delete a session and destroy its sandbox.

        ``DELETE /v1/sessions/{session_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/sessions/{quote(session_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, *, query: Optional["SessionsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "SessionList":
        """
        List the organization's sessions.

        ``GET /v1/sessions``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, session_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Session":
        """
        Retrieve one session.

        ``GET /v1/sessions/{session_id}``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/sessions/{quote(session_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def update(self, session_id: str, body: "SessionPatchRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Session":
        """
        Change a session: title, metadata, instructions, or its safety settings.

        ``PATCH /v1/sessions/{session_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "PATCH",
            f"/sessions/{quote(session_id, safe='')}",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class WebhooksResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, body: "WebhookCreateRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WebhookSubscriptionCreated":
        """
        Subscribe an endpoint to session events.

        ``POST /v1/webhooks``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/webhooks",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, webhook_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Remove a webhook subscription.

        ``DELETE /v1/webhooks/{webhook_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/webhooks/{quote(webhook_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, *, query: Optional["WebhooksListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "WebhookSubscriptionList":
        """
        List the organization's webhook subscriptions.

        ``GET /v1/webhooks``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/webhooks",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class AgentsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, body: "AgentCreateRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Agent":
        """
        Create or replace a named agent.

        ``POST /v1/agents``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/agents",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, agent_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Delete an agent.

        ``DELETE /v1/agents/{agent_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/agents/{quote(agent_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, *, query: Optional["AgentsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "AgentList":
        """
        List the organization's agents.

        ``GET /v1/agents``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/agents",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, agent_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Agent":
        """
        Retrieve one agent.

        ``GET /v1/agents/{agent_id}``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/agents/{quote(agent_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class EnvironmentTemplatesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, body: "AgentCreateRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "EnvironmentTemplate":
        """
        Deprecated alias for POST /agents.

        ``POST /v1/environment-templates``
        Needs the ``sessions:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/environment-templates",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, template_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Deprecated alias for DELETE /agents/{agent_id}.

        ``DELETE /v1/environment-templates/{template_id}``
        Needs the ``sessions:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/environment-templates/{quote(template_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, *, query: Optional["EnvironmentTemplatesListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "EnvironmentTemplateList":
        """
        Deprecated alias for GET /agents.

        ``GET /v1/environment-templates``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/environment-templates",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def retrieve(self, template_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "EnvironmentTemplate":
        """
        Deprecated alias for GET /agents/{agent_id}.

        ``GET /v1/environment-templates/{template_id}``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/environment-templates/{quote(template_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class EnvironmentProfilesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, *, query: Optional["EnvironmentProfilesListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "EnvironmentProfileList":
        """
        List the organization's environment profiles.

        ``GET /v1/environment-profiles``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/environment-profiles",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class ModelConnectorsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def retrieve(self, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ModelConnectorCatalog":
        """
        The model providers this deployment can connect, and their defaults.

        ``GET /v1/model-connectors``
        """
        return self._transport.request(
            "GET",
            f"/model-connectors",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class ModelCredentialsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, body: "ModelCredentialCreateRequest", *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ModelCredential":
        """
        Connect a model provider with one of your own keys.

        ``POST /v1/model-credentials``
        Needs the ``credentials:write`` scope.
        Answers 201.
        """
        return self._transport.request(
            "POST",
            f"/model-credentials",
            body=body,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def delete(self, credential_id: str, *, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "Deleted":
        """
        Remove a model connection.

        ``DELETE /v1/model-credentials/{credential_id}``
        Needs the ``credentials:write`` scope.
        """
        return self._transport.request(
            "DELETE",
            f"/model-credentials/{quote(credential_id, safe='')}",
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

    def list(self, *, query: Optional["ModelCredentialsListQuery"] = None, idempotency_key: Optional[str] = None, timeout: Optional[float] = None) -> "ModelCredentialList":
        """
        List the organization's model connections.

        ``GET /v1/model-credentials``
        Needs the ``sessions:read`` scope.
        """
        return self._transport.request(
            "GET",
            f"/model-credentials",
            query=query,
            idempotency_key=idempotency_key,
            timeout=timeout,
        )

class Resources:
    def __init__(self, transport: Transport) -> None:
        self.health: HealthResource = HealthResource(transport)
        self.sessions: SessionsResource = SessionsResource(transport)
        self.webhooks: WebhooksResource = WebhooksResource(transport)
        self.agents: AgentsResource = AgentsResource(transport)
        self.environment_templates: EnvironmentTemplatesResource = EnvironmentTemplatesResource(transport)
        self.environment_profiles: EnvironmentProfilesResource = EnvironmentProfilesResource(transport)
        self.model_connectors: ModelConnectorsResource = ModelConnectorsResource(transport)
        self.model_credentials: ModelCredentialsResource = ModelCredentialsResource(transport)
